### ISSUE TITLE
[!] GENERAL discussion, feedback, questions belong here!

### ISSUE THREAD

**Issue by Aris-t2** [Aris-t2/CustomCSSforTb#1]
Instead of opening new "issues" for general talk we can use this area for discussions, feedback and questions. Open new "issues" for real bugs and problems.

**This project will not recreate outdated or discontinued add-ons except for CustomizeMyBird.**

CustomCSSforTb does not offer ...
... version numbers for add-ons in add-ons manager add-on lists (Tbs code differs from Fx code in this case, CustomCSSforFx code to restore version number does not work with Tb68+)
... CMBs scrollbar customizations ([JS code required](https://github.com/Aris-t2/CustomCSSforTb/issues/2))
... some other tweaks like "compact" menubar or main toolbar (tweaks become redundant)
... a custom CSS applier ([JS code required](https://github.com/Aris-t2/CustomCSSforTb/issues/2))

**Comment by krystian3w** [comment]
Hello,  

The css "`attachment above mail content`" break splitter to "minimize" this bar:

![](https://i.imgur.com/OQ1GIc7.png) | ![](https://i.imgur.com/0p4Upjw.png) 
--- | ----

Workaround (move to bottom and disable click / touch) :

```css
splitter#attachment-splitter[orient="vertical"][collapsed] {
  display: none;
}
 
splitter#attachment-splitter[orient="vertical"] {
  pointer-events: none;
}
```

---

Also splitters in TB 68.1 is too big with Windows classic theme:
```css
splitter {
    min-width: 4px !important;
    min-height: 4px !important;
}
```

4px is much better as default 6px.

**Comment by krystian3w** [comment]
Hello, active tabs on have changed :x: to png image.  Any updates? Also possible change black mail icon in tab without hard hacks?

**Comment by krystian3w** [comment]
Possible add to templates "`my_userChrome.css`" / "`my_userContent.css`" at bottom?

**Comment by Aris-t2** [comment]
Sure, I can add those on next update.

**Comment by Aris-t2** [comment]
As far as I know this add-on is not about CSS.
Also see op --->

> This project will not recreate outdated or discontinued add-ons except for CustomizeMyBird.

**Comment by GaVenga** [comment]
There is an working update for "Hide Local Folders" for TB
https://addons.thunderbird.net/de/thunderbird/addon/hide-local-folders/

**Comment by JYLD** [comment]
Aris-t2, I have an idea for you.  May not be a good idea.  I've encountered some people who find the idea of installing CustomCSSforTB into their profile and then using a text editor to turn features on or off.  Made me think that a quick down and dirty install gui would help.  A gui app that just installs the css files to the profile and then has a selection list to turn features on and off.  The gui app could make the edits to the relevant css files.  I have no idea how much work creating such a gui install/settings app might be.

One possible positive is that you could charge for the install/settings selection app.  I don't think charging for that stand alone app would violate the open software license that applies to the css files themselves, but I'm not all that knowledgeable on the licensing rules.

**Comment by Aris-t2** [comment]
While I see the advantages of a gui/application, I have no interest in working on something like that. This was asked uncountable times in the CustomCSSforFx area too, but I always told, that people are free to develop a gui/application, if they like, I don't mind.

**Comment by GaVenga** [comment]
**Aris is right.**
I know that it is very hard work; but now i am to old for this. Lifetime expires (= joke)
Younger people do not have any interest in doing that- or what?!

**Comment by JYLD** [comment]
I understand.  I was just throwing that out there, not requesting it.  I'm fine with using things as you have been kind enough to provide them.  Hope you have a great holiday season this year, and thank you for all the work you did on both CMB and CustomCSSforTB !!

**Comment by JoseHidalgo** [comment]
Hi Aris, I'm an active user of your custom CSS tweaks for FF and they work beautifully.

Today I updated TB to 68.5, and of course my UI got all messed up.  So I downloaded your custom CSS tweaks for TB. However, I can't seem to find the same options as with FF. Could you please tell me if these things can be achieved ?
- Tabs below menu bar
- Alternate row colors (in inbox and all other folders containing emails)
- Custom row spacing (in inbox and all other folders containing emails)
- Custom highlight color

Many thanks in advance, and please keep up your excellent work. You are a lifesaver ! :1st_place_medal:

**Comment by JYLD** [comment]
Try using my custom CSS tweaks for TB in a userChrome.css file or in a 
file that is imported into your userChrome.css file in addition to using 
CustomCSSforTB.  Latest version of my tweaks is at 
https://github.com/JYLD/User-CSS-For-Firefox-And-Thunderbird .

*Gary*

**Comment by JoseHidalgo** [comment]
Thanks @JYLD :) No offense, but your userChrome.css looks quite complicated and less "obvious" than Aris' one, and I'm rather a beginner with CSS. Could you please point out which lines I should copy and add to my userChrome.css for the aforementioned things ? Thank you !

PS : I'll make sure to set "Settings/Options > Advanced > General > Config Editor... toolkit.legacyUserProfileCustomizations.stylesheets" to true since I'm running TB 68.5.0

**Comment by JYLD** [comment]
My css tweaks won't do all the things you asked about.  You need to use 
CustomCSSforTB.  My CSS does handle some customized tweaks as an 
enhancement to CustomCSSforTB.  I'm afraid if you want to get your TB 
personalized to your tastes you need to do some reading on the internet 
about CSS.  That will help you understand various CSS tweaks offered by 
others and how to tweak those tweaks to your liking.

If you load my tweaks into notepad and then search for this " /* _Mail 
Folder Tree And Email Thread Tree_ */ " you will find the section about 
the folder pane and thread pane which includes the colored alternating 
backgrounds in the thread pane.

I'm afraid this is all the help I can provide.  Its up to you to learn 
and make use of what's available.

*Gary*

**Comment by JoseHidalgo** [comment]
Let's make it simpler. I have already spent hours on the internet, and I have just solved points 2 and 4 of my previous list: Alternate row colors (in inbox and all other folders containing emails) and     Custom highlight color.

So here's the two things I'm trying to solve:
- Tabs below menu bar
- Custom row spacing (in inbox and all other folders containing emails)

Thanks to anybody who can help with this. @Aris-t2 maybe? *crosses fingers*

**Comment by Aris-t2** [comment]
Custom row spacing

You can alter rows height value using this:

```css
treechildren::-moz-tree-row {
  min-height: 40px !important;
}
```

Can't suggest using padding/margin there without causing glitches.

This project already offers options  for tabs/menubar position through userChrome.css.
https://github.com/Aris-t2/CustomCSSforTb/blob/master/stylesheets/userChrome.css#L139
```css
/* Menubar appearance and position - [only use one at a time] ************************************/
/* @import "./css/general/menubar_above_tabs.css"; /**/
/* @import "./css/general/menubar_below_tabs.css"; /**/
/* @import "./css/general/menubar_below_tabs_aero.css"; /**/
/* @import "./css/general/menubar_below_tabs_with_border.css"; /**/
/* @import "./css/general/menubar_below_tabs_with_border_aero.css"; /**/
```

**Comment by JoseHidalgo** [comment]
I am happy to report that everything works now! Once again @Aris-t2 saved the day.
I used the standard Aris package, with the following additional tweaks:

**1. Custom Row Spacing**
`treechildren::-moz-tree-row {
  min-height: 40px !important;
}`

**2. List Box Alternating Row Background Colors + Highlight Color (Dark Theme)**
`@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);
treechildren::-moz-tree-row(even),
treechildren:hover::-moz-tree-row(even) { background-color: #3c3c3c !important; }
treechildren::-moz-tree-row(odd),
treechildren:hover::-moz-tree-row(odd) { background-color: #333333 !important; }
treechildren::-moz-tree-row(selected),
treechildren:hover::-moz-tree-row(selected) { background-color: -moz-Dialog !important; }
treechildren::-moz-tree-cell-text(selected),
treechildren:hover::-moz-tree-cell-text(selected) { color: -moz-DialogText !important; }
treechildren::-moz-tree-row(selected, focus),
treechildren:hover::-moz-tree-row(selected, focus) { background-color: Highlight !important; }
treechildren::-moz-tree-cell-text(selected, focus),
treechildren:hover::-moz-tree-cell-text(selected, focus) { color: HighlightText !important; }
treechildren::-moz-tree-cell(unread) { background-color: #339966 !important; }
treechildren::-moz-tree-cell(unread,selected) {	background-color: #339966 !important; }
treechildren:-moz-tree-cell-text(unread) { color: #ffffcc !important; font-style: italic !important; }`

**Comment by JoseHidalgo** [comment]
With that said, I only have one question. Currently my buttons look like this, in both the button bar ("1") and the new email window ("2"):

![2020 02 19 - 00 21 59](https://user-images.githubusercontent.com/10851603/74787570-c7057700-52af-11ea-8a9f-26036bdc487f.jpg)

As you can see they're not very readable or consistent with the rest of the theme. Is there a way to change that ? Thanks again !

**Comment by Aris-t2** [comment]
You could change the colors / transparency values of the button background in `ctb_on_main_toolbars.css`.

**Comment by Acid-Crash** [comment]
Hi @Aris-t2 
I am trying to inspect the classes within messageList/MainList pane.
I am able to open regular devTools (Tools > Developer Tools > Developer Toolbox). 
However later I am unable to go deeper through `treechildren` element...
Could you please give some hints on how to do investigate the mentioned pane structure?

**Comment by Aris-t2** [comment]
It was never possible to inspect treechildren code, old Fx/Tb inspect tools also suffered from this.
The only way is to dig though css files and look for the code.

**Comment by Acid-Crash** [comment]
Ohh, that is sad. thx for the tip.

**Comment by JoseHidalgo** [comment]
Thanks @Aris-t2 for your tip. I managed to change the colors in ctb_on_main_toolbar.css . Not being a CSS expert, I fiddled a bit with it, and I achieved something darker and more "flat design", lol:

`/*		background: rgba(151,152,153,.05)
					linear-gradient(rgba(251,252,253,.95), rgba(246,247,248,.47) 49%, 
											rgba(231,232,233,.45) 51%, rgba(225,226,229,.3)) !important; */
		background: rgba(50,50,52) !important;

		background-clip: padding-box !important;
		border-radius: 2.5px !important;
		border: 1px solid !important;

/*		border-color: rgba(0,0,0,.12) rgba(0,0,0,.19) rgba(0,0,0,.38) !important; */
		border-color: rgba(50,50,52) !important;

/*		box-shadow: 0 0 0 1px rgba(255,255,255,.3) inset,
					0 0 0 2px rgba(255,255,255,.1) inset !important; */
`

**Comment by JoseHidalgo** [comment]
BTW here's a new question: is there a way to change the color of the rectangular zone that appears only when an email has attached documents? Seeing it pop up in a different color would make it much easier to realize that an email has an attached document. Thanks!

![2020 02 27 - 13 14 38](https://user-images.githubusercontent.com/10851603/75444893-9b942380-5964-11ea-9157-d5d665211b79.jpg)

**Comment by Aris-t2** [comment]
Test this:
```css
#attachmentView {
  background:  blue !important;
}
```

**Comment by JoseHidalgo** [comment]
Thanks! Sadly that doesn't work at the moment, so I must be doing something wrong.
I have added the code to my userChrome.css file and restarted TB.

**Comment by Aris-t2** [comment]
I posted the "wrong" code. Try the updated one, it worked for me with Tb 68.5.

**Comment by JoseHidalgo** [comment]
Oh yes, that definitely worked now. Many thanks again!!

**Comment by Thalon77** [comment]
Trying to move the tabs below the menubar, tried activating the line @import "./css/general/menubar_above_tabs.css but the result is the same (see attached screenshot), what am I doing wrong?
![Cattura](https://user-images.githubusercontent.com/33811707/75821735-0bf4d780-5d9f-11ea-9a15-e5de0a87d1d7.JPG)

**Comment by Aris-t2** [comment]
There is no menu bar in your screenshot.

The menu bar is the one with "File, Edit...." on it not the main toolbar shown below your tabs toolbar. Tabs can not be placed below the main toolbar.

There are only these two cases:
![image](https://user-images.githubusercontent.com/6013569/75822544-6fcbd000-5da0-11ea-8ee0-ae5e8e778c25.png)

**Comment by Thalon77** [comment]
Thanks for the explaination.
I imagine that that is also due to the recent changes in Thunderbird's code, right?

**Comment by Aris-t2** [comment]
It was always like this.

**Comment by krystian3w** [comment]
TB 78 may need supdate ome update CSS for "settings" tab, when we have active dark mode in Windows 10.

![Przechwytywanie](https://user-images.githubusercontent.com/35370833/91017786-fd210c00-e5ee-11ea-9ddd-d3e7f4cdb351.JPG) |
--- |


No I can't see any text in "settings", but "`about:addons`" have property colors (black/dark background instead of light "white").

**Comment by Fredrik-69** [comment]
> 
> 
> TB 78 may need update some update CSS for "settings" tab, when we have active dark mode in Windows 10.
> ![Przechwytywanie](https://user-images.githubusercontent.com/35370833/91017786-fd210c00-e5ee-11ea-9ddd-d3e7f4cdb351.JPG)
> 
> No I can't see any text in "settings", but "`about:addons`" have property colors (black/dark background instead of light "white").

I found out that you can "override" the dark colors in TB (if you use the Windows 10 dark theme) like this:

- In Thunderbird, open the Advanced config editor.
- Create new Integer: 'ui.systemUsesDarkTheme'
- Set to 0 for overriding of system dark mode.
- Restart Thunderbird!

Then you are more or less back to the colors in TB68.

**Comment by Aris-t2** [comment]
Dark mode set by the OS is not detectable CSS-wise. I think everything will work once Thunderbrid adds dark theme support for all about:pages.

**Comment by Gittyperson** [comment]
Thanks again for your work. TB adds a title bar (Windows 10) when mail.tabs.autoHide=true. Is there a way to make it go a-way?

**Comment by click-click** [comment]
I am currently testing TB 78.3.2 and adapting it to some of my previous settings from TB 68.10, but I've run into a problem trying to reduce the spacing between each thread entry. So far, everything I've tried had no effect. I managed to reduce the spacing on the folders side, but not on the thread side. I used the following for the folder pane and did the same for the thread pane. Anyone have an idea why the thread spacing doesn't get reduced?
`   /********************************
      Set Font Size in Folder Pane
   ********************************/

 #folderTree >treechildren::-moz-tree-cell-text {
    font-size:  10pt !important;
    font-family: Arial !important;
    }

   /***********************
      Folder list spacing
   ***********************/

 #folderTree treechildren::-moz-tree-row {
   min-height: 18px !important;
 }
 
 #threadTree >treechildren::-moz-tree-cell-text {
    font-size: 10pt !important;
    font-family: Arial !important;
    }

   /***********************
      Thread list spacing
   ***********************/

 #threadTree treechildren::-moz-tree-row {
    min-height: 18px !important;
 }`
TB 68
![Spacing68](https://user-images.githubusercontent.com/8570365/96311499-e2c14880-1009-11eb-82cc-9d7bd8cce0a3.png)
TB78
![Spacing78](https://user-images.githubusercontent.com/8570365/96311503-e3f27580-1009-11eb-9124-c3771b246e13.png)

**Comment by Aris-t2** [comment]
This is the most compact tree view I was able to create:

```css
treechildren::-moz-tree-cell-text {
  font-size: 10pt !important;
  font-family: Arial !important;
}
treechildren::-moz-tree-row {
  min-height: 16px !important;
  height: 16px !important;
}
treechildren::-moz-tree-image {
  margin-top: -2px !important;
}
```

**Comment by click-click** [comment]
Wow... that did the trick. I can play with that... Thanks Aris

**Comment by explor202** [comment]
I'm new to TB and have it set up pretty much the way I want it. The only thing left is for me to change the color of the progress bar from green to something like an orange color. Can anyone point me in the right direction?

**Comment by CO-Windler** [comment]
I have trouble with replacing all default folder icons with coloured icons and yet had only partial success. 

To customize the button and folder icons, I created in my profile the chrome and chrome/image subfolders and created userChrome.css following these instructions.

Colored icons for folders:
https://support.mozilla.org/en-US/questions/1309818

Modifying Mozilla Thunderbird-68 buttons with userChrome.css:
https://stackoverflow.com/questions/57201164/modifying-mozilla-thunderbird-68-buttons-with-userchrome-css

I had to copy *both* contents into userChrome.css, because having only the 2nd will show corrupted folder icons. The used icons need to be in the chrome/image subfolder of the profile. I used these PNG files from the CustomizeMyBird project.

https://github.com/Aris-t2/CustomizeMyBird/tree/master/xpi/content/images

tb_compose_tb*.png
tb_folder_tb*.png
tb_mail_tb*.png

Use in userChrome.css the tb* number of the corresponding old Thunderbird version.

Unfortunately I still get no coloured icons in the context menu of an e-mail (destinations of move, copy etc.). Also the folder icons for "sent" etc. are only a generic yellow folder icon, but this is still much better than the default paper plane. (I detest the Telegram messenger and do not want any lookalike of that bigdata-paid surveilance infested app.)

**Comment by Aris-t2** [comment]
@explor202 
Which progress bar are you referring to?

@CO-Windler 
Changing folder icons inside mail tree is not supported by CustomCSSforFx since Tb78.

![image](https://user-images.githubusercontent.com/6013569/130094533-db856ae6-2c73-4309-8268-b025c4b22691.png)

This projects files do not target icons in context menus, but custom code is able to modify them:

```css
.folderMenuItem {
    fill: blue !important;
}
```

**Comment by Thalon77** [comment]
I need to fix a thing if possible, the "action icons" you see over an highlighted message (see attached image), i need that border around them gone but I don't know which option I have to edit inside the CSS, I'm quite sure that the border around them wasn't there, something changed after Thunderbird was updated a while ago (using V 91.3.0 now and V 1.12 of the CSS).

![Cattura](https://user-images.githubusercontent.com/33811707/141135103-666d7ba3-ff19-4c96-bc73-886c40d0e345.JPG)

**Comment by Aris-t2** [comment]
Either disable `ctb_on_main_toolbars.css` inside `userChrome.css` or edit `ctb_on_main_toolbars.css` file an remove all `#header-view-toolbox` entries (incl. the `,` after them).

**Comment by Roxie2401** [comment]
Is there a way in CustomCSSforTB to specify different colors for email accounts similar to the old Add-On "Account Colors" did?  It allowed to set a color for each email account that would show in the Unified Folder Tree, the Message Pane, and the Compose (Write) pain --- maybe like the first account would be Red, the second Green, etc.  I don't know that much about CSS but I know that tab colors, etc. can be set in the User Chrome config, etc.

Just hoping there is a way to get that old Add_on incorporated some way.  I have gone back to Version 68 of TB just to keep that one add-on working.  Not a programmer so don't know if Style Sheets can do this or not.  Thanks for your help and suggestions.  
![Clipboard01](https://user-images.githubusercontent.com/58607543/159016409-d1160f73-04b2-4d31-b594-1376b349d9c1.jpg)
